### ISSUE TITLE
RuntimeError: filter footprint array has incorrect shape

### ISSUE THREAD

**Issue by researcherys** [DanilKonon/FilamentTracking#1]
Running tif with the following properties:
ImageJ=1.53e
images=81
slices=81
fps=30.07157033740302
loop=false

gives:
 
Traceback (most recent call last):
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sam/PycharmProjects/NEW/images/main.py", line 577, in <module>
    main(pargs)
  File "/home/sam/PycharmProjects/NEW/images/main.py", line 569, in main
    tf = TiffVideo(params)
  File "/home/sam/PycharmProjects/NEW/images/main.py", line 402, in __init__
    self._process_file(params['file_path'])
  File "/home/sam/PycharmProjects/NEW/images/main.py", line 440, in _process_file
    processed_pict = process_pict_for_fire(pict)
  File "/home/sam/PycharmProjects/NEW/images/fire.py", line 639, in process_pict_for_fire
    mean_picture = median(agg_picture, selem=np.ones(shape=[3, 3]))
  File "/usr/local/lib/python3.7/dist-packages/skimage/filters/rank/generic.py", line 159, in func_out
    return func(image, selem=selem, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/skimage/filters/_median.py", line 97, in median
    cval=cval)
  File "/usr/local/lib/python3.7/dist-packages/scipy/ndimage/filters.py", line 1241, in median_filter
    origin, 'median')
  File "/usr/local/lib/python3.7/dist-packages/scipy/ndimage/filters.py", line 1128, in _rank_filter
    raise RuntimeError('filter footprint array has incorrect shape.')
RuntimeError: filter footprint array has incorrect shape.

Problem is:  len(fshape) == 2 , while input.ndim == 3.

What could be wrong? (Feel free write Russian.)

**Comment by DanilKonon** [comment]
I think this may be problem with skimage. What version do you use? I use 0.15.0.

**Comment by researcherys** [comment]
used scikit-image==0.16.2 as in requirements.txt. Should I degrade to 0.15.0?

**Comment by researcherys** [comment]
Tried  it(scikit-image==0.15.0). This time:

Traceback (most recent call last):
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sam/PycharmProjects/NEW/images/main.py", line 577, in <module>
    main(pargs)
  File "/home/sam/PycharmProjects/NEW/images/main.py", line 569, in main
    tf = TiffVideo(params)
  File "/home/sam/PycharmProjects/NEW/images/main.py", line 402, in __init__
    self._process_file(params['file_path'])
  File "/home/sam/PycharmProjects/NEW/images/main.py", line 440, in _process_file
    processed_pict = process_pict_for_fire(pict)
  File "/home/sam/PycharmProjects/NEW/images/fire.py", line 639, in process_pict_for_fire
    mean_picture = median(agg_picture, selem=np.ones(shape=[3, 3]))
  File "/usr/local/lib/python3.7/dist-packages/skimage/filters/rank/generic.py", line 153, in func_out
    return func(image, selem=selem, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/skimage/filters/_median.py", line 93, in median
    shift_x=shift_x, shift_y=shift_y)
  File "/usr/local/lib/python3.7/dist-packages/skimage/filters/rank/generic.py", line 153, in func_out
    return func(image, selem=selem, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/skimage/filters/rank/generic.py", line 534, in median
    shift_x=shift_x, shift_y=shift_y)
  File "/usr/local/lib/python3.7/dist-packages/skimage/filters/rank/generic.py", line 113, in _apply_scalar_per_pixel
    out_dtype)
  File "/usr/local/lib/python3.7/dist-packages/skimage/filters/rank/generic.py", line 68, in _handle_input
    assert_nD(image, 2)
  File "/usr/local/lib/python3.7/dist-packages/skimage/_shared/utils.py", line 176, in assert_nD
    raise ValueError(msg_incorrect_dim % (arg_name, '-or-'.join([str(n) for n in ndim])))
ValueError: The parameter `image` must be a 2-dimensional array

**Comment by DanilKonon** [comment]
Maybe your images are coloured (RGB)?
